import type { Metadata } from "next"
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter'
import { Container, CssBaseline, ThemeProvider, Typography } from "@mui/material"
import theme from "@/app/theme"
import packageJson from '../../package.json'
import { SessionProvider } from '@/components/providers/SessionProvider'

// TODO: Fill up correct metadata + favicon when provided
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <SessionProvider>
          <AppRouterCacheProvider>
            <ThemeProvider theme={theme}>
              <CssBaseline />
              {children}
            </ThemeProvider>
          </AppRouterCacheProvider>
        </SessionProvider>
        <Container maxWidth="lg" sx={{ mt: 4, mb: 4 }}>
          <Typography variant="body2" color="textSecondary" align="center">
            v{packageJson.version}
          </Typography>
        </Container>
      </body>
    </html>
  )
}
