# 🛠️ Použij oficiální Go image pro build
FROM golang:1.24 AS builder

WORKDIR /app

COPY go.mod go.sum docs ./
RUN go mod tidy

COPY . .

RUN go build -o pdf-generator ./main.go

# 🚀 Použij lehčí image pro běh aplikace
FROM debian:bookworm-slim AS runtime

WORKDIR /app

COPY --from=builder /app/pdf-generator .

EXPOSE 8080

CMD ["./pdf-generator"]
